import { Document } from 'mongoose'

export interface INOTARYDATA extends Document {
  certfilename: string
  certfileUrl: string
  certfileLocation: string,
  certfileSource: string,
  certfileAddedAt: Date,
  buyDCCertfilename: string
  buyDCCertfileUrl: string
  buyDCCertfileLocation: string,
  buyDCCertfileSource: string,
  buyDCCertfileAddedAt: Date,
  buyDCCertfilePassword: string,
  sealfilename: string
  sealdata: string
  buyPngSealfilename: string
  buyPngSealdata: string
  commissionExpiresOn: number
  dcpassword: string
  county: string
  userId: string
  email: string
  fileKey: string,
  buyDCfileKey: string,
  notaryCertificates: any[],
  notaryCopyOfCommissionLetterName: string,
  notaryCopyOfCommissionLetterUrl: string,
  notaryCopyOfCommissionLetterKey: string,
  stripeAccountName: string,
  stripeAccountLink: string,
  stripeAccountLoginLink: string,
  stripeLoginLinkCreatedAt: number,
  stripeAccountLinkValidTill: number,
  upgradeStripeSessionId: string,
  buyDCStripeSessionId: string,
  buyDCActionDate: Date,
  buyDCPurchaseExpiryDate: Date,
  buyDCPurchaseDate: Date,
  buySealStripeSessionId: string,
  buySealActionDate: Date,
  buySealPurchaseExpiryDate: Date,
  buySealPurchaseDate: Date,
  buyComboStripeSessionId: string,
  buyComboActionDate: Date,
  buyComboPurchaseExpiryDate: Date,
  buyComboPurchaseDate: Date,
  forceSubscriptionCustomerId: string,
  subscriptionCustomerId: string,
  subscriptionExpiresOn: number,
  lsaApprovalLetterKey: string,
  lsaApprovalLetterName: string,
  lsaApprovalLetterUrl: string,
  lsaApprovalLetterUploadedAt: Date,
  loanSigningRONExperience: string,
  hundredRONcompletionProofKey: string,
  hundredRONcompletionProofName: string,
  hundredRONcompletionProofUrl: string,
  hundredRONcompletionProofUploadedAt: Date,
  eoInsuranceProofKey: string,
  eoInsuranceProofName: string,
  eoInsuranceProofUrl: string,
  eoInsuranceProofUploadedAt: Date,
  spanishLanguageFluency: boolean
}
